# ifndef UI_EN_RES
# define UI_EN_RES

#include "fxtypes.h"


EXPORT_STRING(RESID_UI_MNU_FILE 		,TCHAR("&File"))
EXPORT_STRING(RESID_UI_MNU_FILE_VOLINFO	,TCHAR("Volume Info"))
EXPORT_STRING(RESID_UI_MNU_EDIT			,TCHAR("&Edit"))
EXPORT_STRING(RESID_UI_MNU_ABOUT		,TCHAR("&About"))

EXPORT_STRING(RESID_UI_WARNING			,TCHAR("Warning"))
EXPORT_STRING(RESID_UI_STOP				,TCHAR("Stop"));
EXPORT_STRING(RESID_DESKTOP_NO_HANDLER	,TCHAR("Cannot Open Unknown File Type."))


//#define RESID_DESKTOP_NO_HANDLER		(1)



#endif
