#ifndef __FXOS_CON_SDK_EXPORTS_IDX__
#define __FXOS_CON_SDK_EXPORTS_IDX__

   #define EXPORT_CON_BASE   (0)
   #define EXPORT_CON_INITIALIZETEXT                        (EXPORT_CON_BASE + 0)
   #define EXPORT_CON_INITIALIZETEXTFONTS                   (EXPORT_CON_BASE + 1)
   #define EXPORT_CON_GETCONSOLEVISIBLECOLUMNS              (EXPORT_CON_BASE + 2)
   #define EXPORT_CON_GETCONSOLECOLUMNSPERLINE              (EXPORT_CON_BASE + 3)
   #define EXPORT_CON_GETCONSOLEVISIBLELINES                (EXPORT_CON_BASE + 4)
   #define EXPORT_CON_GETCONSOLEMAXLINES                    (EXPORT_CON_BASE + 5)
   #define EXPORT_CON_CONSOLEENABLEBORDER                   (EXPORT_CON_BASE + 6)
   #define EXPORT_CON_CONSOLEDISABLEBORDER                  (EXPORT_CON_BASE + 7)
   #define EXPORT_CON_SETCONSOLEBORDERCOLOR                 (EXPORT_CON_BASE + 8)
   #define EXPORT_CON_SETCONSOLEBORDER                      (EXPORT_CON_BASE + 9)
   #define EXPORT_CON_SETCONSOLEFONTPAGE                    (EXPORT_CON_BASE + 10)
   #define EXPORT_CON_SETCONSOLECURSOR                      (EXPORT_CON_BASE + 11)
   #define EXPORT_CON_SETCONSOLECURSORPOSITION              (EXPORT_CON_BASE + 12)
   #define EXPORT_CON_SETCONSOLECLEARSCREEN                 (EXPORT_CON_BASE + 13)
   #define EXPORT_CON_CONSOLEPRINT                          (EXPORT_CON_BASE + 14)
   #define EXPORT_CON_CONSOLEPRINTCHAR                      (EXPORT_CON_BASE + 15)
   #define EXPORT_CON_CONSOLEPRINTSTRING                    (EXPORT_CON_BASE + 16)
   #define EXPORT_CON_CONSOLEPRINTBUFFER                    (EXPORT_CON_BASE + 17)
   #define EXPORT_CON_SETCONSOLECOLOR                       (EXPORT_CON_BASE + 18)
   #define EXPORT_CON_CREATECONSOLEDIALOG                   (EXPORT_CON_BASE + 19)
   #define EXPORT_CON_CREATECONSOLEWINDOW                   (EXPORT_CON_BASE + 20)

#endif