/*
 * FXOS_GUI_DISPATCH_SDK.c
 * Jun 25, 2021 8:10:28 PM
 */

void _k_initialize_GUI_call_table(PFXZERPOPAGE pzp,UINT tableType)
{

EXPORT_GUI(EXPORT_GUI_CREATEWINDOWCLASS,	k_user_CreateWindowClass);
EXPORT_GUI(EXPORT_GUI_CREATEWINDOWCLASSEX,	k_user_CreateWindowClassEx);
EXPORT_GUI(EXPORT_GUI_REGISTERWINDOWCLASS,	k_user_RegisterWindowClass);
EXPORT_GUI(EXPORT_GUI_CREATEWINDOW,	k_user_CreateWindow);
EXPORT_GUI(EXPORT_GUI_CREATEWINDOWEX,	k_user_CreateWindowEx);
EXPORT_GUI(EXPORT_GUI_SETWINDOWDATA,	k_user_SetWindowData);
EXPORT_GUI(EXPORT_GUI_GETWINDOWDATA,	k_user_GetWindowData);
EXPORT_GUI(EXPORT_GUI_LOADDIALOG,	k_user_LoadDialog);
EXPORT_GUI(EXPORT_GUI_CLOSEWINDOW,	k_user_CloseWindow);
EXPORT_GUI(EXPORT_GUI_DESTROYWINDOW,	k_user_DestroyWindow);
EXPORT_GUI(EXPORT_GUI_REGISTERMOUSEPOINTERCLASS,	k_user_RegisterMousePointerClass);
EXPORT_GUI(EXPORT_GUI_REGISTERFONTCLASS,	k_user_RegisterFontClass);
EXPORT_GUI(EXPORT_GUI_GETFONTCLASS,	k_user_getFontClass);
EXPORT_GUI(EXPORT_GUI_GETMOUSEPOINTERCLASS,	k_user_getMousePointerClass);
EXPORT_GUI(EXPORT_GUI_SETMOUSEPOINTER,	k_user_setMousePointer);
EXPORT_GUI(EXPORT_GUI_SHOWWINDOW,	k_user_ShowWindow);
EXPORT_GUI(EXPORT_GUI_CLIENTTOGLOBALCOORDINATES,	k_user_ClientToGlobalCoordinates);
EXPORT_GUI(EXPORT_GUI_GLOBALTOCLIENTCOORDINATES,	k_user_GlobalToClientCoordinates);
EXPORT_GUI(EXPORT_GUI_CREATEMENU,	k_user_CreateMenu);
EXPORT_GUI(EXPORT_GUI_CREATEMENURESOURCE,	k_user_CreateMenuResource);
EXPORT_GUI(EXPORT_GUI_ADDMENUITEM,	k_user_AddMenuItem);
EXPORT_GUI(EXPORT_GUI_SETMENUITEMATTRIBUTE,	k_user_SetMenuItemAttribute);
EXPORT_GUI(EXPORT_GUI_SETMENUSTATE,	k_user_SetMenuState);
EXPORT_GUI(EXPORT_GUI_CREATEBUTTON,	k_user_CreateButton);
EXPORT_GUI(EXPORT_GUI_CREATETEXTBOX,	k_user_CreateTextBox);
EXPORT_GUI(EXPORT_GUI_CREATEVERTICALSCROLLBAR,	k_user_CreateVerticalScrollBar);
EXPORT_GUI(EXPORT_GUI_CREATEHORIZONTALSCROLLBAR,	k_user_CreateHorizontalScrollBar);
EXPORT_GUI(EXPORT_GUI_CREATEMSGBOX,	k_user_CreateMsgBox);
EXPORT_GUI(EXPORT_GUI_CENTERWINDOW,	k_user_CenterWindow);
EXPORT_GUI(EXPORT_GUI_CENTERBOTTOMWINDOW,	k_user_CenterBottomWindow);
EXPORT_GUI(EXPORT_GUI_MOVEWINDOW,	k_user_MoveWindow);
EXPORT_GUI(EXPORT_GUI_MOVEWINDOWEX,	k_user_MoveWindow_ex);
EXPORT_GUI(EXPORT_GUI_RESIZEWINDOWEX,	k_user_ResizeWindow_ex);
EXPORT_GUI(EXPORT_GUI_GETFOCUSWINDOW,	k_user_getFocusWindow);
EXPORT_GUI(EXPORT_GUI_ISCHILDWINDOW,	k_user_IsChildWindow);
EXPORT_GUI(EXPORT_GUI_SETRECT,	k_user_SetRect);
EXPORT_GUI(EXPORT_GUI_CLEARRECT,	k_user_ClearRect);
EXPORT_GUI(EXPORT_GUI_COPYRECT,	k_user_CopyRect);
EXPORT_GUI(EXPORT_GUI_DRAWTEXT,	k_user_DrawText);
EXPORT_GUI(EXPORT_GUI_DRAWWINDOWTEXTTOPOINT,	k_user_DrawWindowTextToPointWithFont);
EXPORT_GUI(EXPORT_GUI_GETMOUSEPOINT,	k_user_GetMousePoint);
EXPORT_GUI(EXPORT_GUI_GETMOUSECLIENTPOINT,	k_user_GetMouseClientPoint);

}
