/*
 * FXOS_GFX_DISPATCH_SDK.c
 * Jul 29, 2021 10:56:51 PM
 */
#include "fxkernel.h"
#include "fxdos.h"
#include "fx_exports.h"
#include "GFX_IDX_SDK.h"
void _k_initialize_GFX_call_table(PFXZEROPAGE pzp)
{

EXPORT_GFX(EXPORT_GFX_DRAWMENU,	k_draw_menu);
EXPORT_GFX(EXPORT_GFX_GETUIBACKGROUNDCOLOR,	k_getUIBackgroundColor);
EXPORT_GFX(EXPORT_GFX_GETUIDESKTOPCOLOR,	k_getUIDesktopColor);
EXPORT_GFX(EXPORT_GFX_GETUIFONTCOLOR,	k_getUIFontColor);
EXPORT_GFX(EXPORT_GFX_GETUISELECTEDCOLOR,	k_getUIFontSelectedColor);
EXPORT_GFX(EXPORT_GFX_GETUIHIGHLIGHTCOLOR,	k_getUIHighlightColor);
EXPORT_GFX(EXPORT_GFX_GETUIWINDOWFRAMECOLOR,	k_getUIWindowFrameColor);
EXPORT_GFX(EXPORT_GFX_GETUIWINDOWBORDERCOLOR,	k_getUIWindowBorderColor);
EXPORT_GFX(EXPORT_GFX_GETUIWINDOWSHADECOLOR,	k_getUIWindowShadowColor);
EXPORT_GFX(EXPORT_GFX_GETUIMENUCOLOR,	k_getUIMenuColor);
EXPORT_GFX(EXPORT_GFX_GETUIGADGETCOLOR,	k_getUIGadgetColor);
EXPORT_GFX(EXPORT_GFX_GETUICOLORMETRIC,	k_getUIColor);
EXPORT_GFX(EXPORT_GFX_HWNDTORECT,	k_HWNDToWINRECT);
EXPORT_GFX(EXPORT_GFX_ENABLETEXTMODE,	k_enable_text_mode);
EXPORT_GFX(EXPORT_GFX_ENABLEBITMAPMODE,	k_enable_bitmap_mode);
EXPORT_GFX(EXPORT_GFX_GETVIDEOMODE,	k_get_video_mode);
EXPORT_GFX(EXPORT_GFX_GETPIXELOFFSET,	k_gui_get_pixel_offset);
EXPORT_GFX(EXPORT_GFX_GETPIXELWIDTH,	k_gui_get_pixel_offset_width);
EXPORT_GFX(EXPORT_GFX_SETDEFAULTCOLORS,	setColors);
EXPORT_GFX(EXPORT_GFX_GFXCOPYRECT,	k_copy_rect);
EXPORT_GFX(EXPORT_GFX_GFXSETRECT,	k_set_rect);
EXPORT_GFX(EXPORT_GFX_GFXRECTINSIDE,	k_is_inside_rect);
EXPORT_GFX(EXPORT_GFX_GFXRECTOVERLAPPED,	k_is_overlapped_rect);
EXPORT_GFX(EXPORT_GFX_GFXRECTOVERLAPPEDPOINT,	k_is_overlapped_rect_points);
EXPORT_GFX(EXPORT_GFX_GFXBITBLT,	k_bitblt);
EXPORT_GFX(EXPORT_GFX_GFXBANKBITBLT,	k_memory_bitblt);
EXPORT_GFX(EXPORT_GFX_DRAWPIXEL,	k_draw_pixel);
EXPORT_GFX(EXPORT_GFX_DRAWPIXELEX,	k_draw_pixel_ex);
EXPORT_GFX(EXPORT_GFX_DRAWPIXELFRONT,	k_draw_pixel_front);
EXPORT_GFX(EXPORT_GFX_DRAWPIXELBACK,	k_draw_pixel_back);
EXPORT_GFX(EXPORT_GFX_DRAWPIXELBANK,	k_draw_pixel_D0);
EXPORT_GFX(EXPORT_GFX_DRAWSEGMENTS,	k_draw_segments);
EXPORT_GFX(EXPORT_GFX_DRAWCIRCLE,	k_draw_circle);
EXPORT_GFX(EXPORT_GFX_DRAWFILLEDCIRCLE,	k_draw_filled_circle);
EXPORT_GFX(EXPORT_GFX_DRAWLINE,	k_draw_line);
EXPORT_GFX(EXPORT_GFX_DRAWLINEEX,	k_draw_line_ex);
EXPORT_GFX(EXPORT_GFX_DRAWRECTANGLE,	k_draw_rect);
EXPORT_GFX(EXPORT_GFX_DRAWFILLEDRECTANGLE,	k_vdraw_filled_rect);
EXPORT_GFX(EXPORT_GFX_DRAWTEXTWITHFONT,	k_draw_text_point_with_font);
EXPORT_GFX(EXPORT_GFX_DRAWTEXTWITHFONTEX,	k_draw_text_point_with_font_ex);
EXPORT_GFX(EXPORT_GFX_GETFONTMETRICS,	k_get_font_metrics);
EXPORT_GFX(EXPORT_GFX_DRAWTEXTSCALED,	k_draw_char_scaled);
EXPORT_GFX(EXPORT_GFX_DRAWWINDOWGADGET,	k_put_wingadget_point);
EXPORT_GFX(EXPORT_GFX_DRAWWINDOWGADGETEX,	k_put_wingadget_point_ex);
EXPORT_GFX(EXPORT_GFX_DRAWWINDOWWIDGET,	k_gui_DrawWidget);
EXPORT_GFX(EXPORT_GFX_DRAWWINDOWICON,	k_put_winicon_point);
EXPORT_GFX(EXPORT_GFX_DRAWWINDOWICONEX,	k_put_winicon_point_ex);
EXPORT_GFX(EXPORT_GFX_DRAWWINDOWICONSCALED,	k_put_winicon_scaled);
EXPORT_GFX(EXPORT_GFX_GETFONTHEIGHT,	k_font_getFontHeight);
EXPORT_GFX(EXPORT_GFX_GETFONTWIDTH,	k_font_getFontWidth);
EXPORT_GFX(EXPORT_GFX_MOUSEPOINTERINIT,	k_gui_init_mousepointer);
EXPORT_GFX(EXPORT_GFX_SETMOUSEPOINTERDATA,	k_gui_set_mousepointer);

}
