/*
 * FXOS_CON_DISPATCH_SDK.c
 * Jun 25, 2021 8:10:28 PM
 */

void _k_initialize_CON_call_table(PFXZERPOPAGE pzp,UINT tableType)
{

EXPORT_CON(EXPORT_CON_INITIALIZETEX,	k_initialize_text);
EXPORT_CON(EXPORT_CON_INITIALIZETEXTFONTS,	k_initialize_text_fonts);
EXPORT_CON(EXPORT_CON_GETCONSOLEVISIBLECOLUMNS,	k_get_cols_visible);
EXPORT_CON(EXPORT_CON_GETCONSOLECOLUMNSPERLINE,	k_get_cols_per_line);
EXPORT_CON(EXPORT_CON_GETCONSOLEVISIBLELINES,	k_get_lines_visible);
EXPORT_CON(EXPORT_CON_GETCONSOLEMAXLINES,	k_get_lines_max);
EXPORT_CON(EXPORT_CON_CONSOLEENABLEBORDER,	k_enable_border);
EXPORT_CON(EXPORT_CON_CONSOLEDISABLEBORDER,	k_disable_border);
EXPORT_CON(EXPORT_CON_SETCONSOLEBORDERCOLOR,	k_set_border_color);
EXPORT_CON(EXPORT_CON_SETCONSOLEBORDER,	k_set_border);
EXPORT_CON(EXPORT_CON_SETCONSOLEFONTPAGE,	k_set_text_font_page);
EXPORT_CON(EXPORT_CON_SETCONSOLECURSOR,	k_enable_text_cursor);
EXPORT_CON(EXPORT_CON_SETCONSOLECURSORPOSITION,	k_set_cursor_position);
EXPORT_CON(EXPORT_CON_SETCONSOLECLEARSCREEN,	k_clear_screen);
EXPORT_CON(EXPORT_CON_CONSOLEPRINT,	k_print);
EXPORT_CON(EXPORT_CON_CONSOLEPRINTCHAR,	k_put_char);
EXPORT_CON(EXPORT_CON_CONSOLEPRINTSTRING,	k_put_string);
EXPORT_CON(EXPORT_CON_CONSOLEPRINTBUFFER,	k_put_string_buffer);
EXPORT_CON(EXPORT_CON_SETCONSOLECOLOR,	k_put_color);
EXPORT_CON(EXPORT_CON_CREATECONSOLEDIALOG,	k_text_mode_dialog);
EXPORT_CON(EXPORT_CON_CREATECONSOLEWINDOW,	k_create_text_window);

}
