#ifndef __FXOS_GFX_SDK_EXPORTS_IDX__
#define __FXOS_GFX_SDK_EXPORTS_IDX__

   #define EXPORT_GFX_BASE   (0)
   #define EXPORT_GFX_DRAWMENU                              (EXPORT_GFX_BASE + 0)
   #define EXPORT_GFX_GETUIBACKGROUNDCOLOR                  (EXPORT_GFX_BASE + 1)
   #define EXPORT_GFX_GETUIDESKTOPCOLOR                     (EXPORT_GFX_BASE + 2)
   #define EXPORT_GFX_GETUIFONTCOLOR                        (EXPORT_GFX_BASE + 3)
   #define EXPORT_GFX_GETUISELECTEDCOLOR                    (EXPORT_GFX_BASE + 4)
   #define EXPORT_GFX_GETUIHIGHLIGHTCOLOR                   (EXPORT_GFX_BASE + 5)
   #define EXPORT_GFX_GETUIWINDOWFRAMECOLOR                 (EXPORT_GFX_BASE + 6)
   #define EXPORT_GFX_GETUIWINDOWBORDERCOLOR                (EXPORT_GFX_BASE + 7)
   #define EXPORT_GFX_GETUIWINDOWSHADECOLOR                 (EXPORT_GFX_BASE + 8)
   #define EXPORT_GFX_GETUIMENUCOLOR                        (EXPORT_GFX_BASE + 9)
   #define EXPORT_GFX_GETUIGADGETCOLOR                      (EXPORT_GFX_BASE + 10)
   #define EXPORT_GFX_GETUICOLORMETRIC                      (EXPORT_GFX_BASE + 11)
   #define EXPORT_GFX_HWNDTORECT                            (EXPORT_GFX_BASE + 12)
   #define EXPORT_GFX_DRAWPIXEL                             (EXPORT_GFX_BASE + 13)
   #define EXPORT_GFX_SETFOREGROUNDCOLOR                    (EXPORT_GFX_BASE + 14)
   #define EXPORT_GFX_SETBACKGROUNDCOLOR                    (EXPORT_GFX_BASE + 15)
   #define EXPORT_GFX_ENABLETEXTMODE                        (EXPORT_GFX_BASE + 16)
   #define EXPORT_GFX_ENABLEBITMAPMODE                      (EXPORT_GFX_BASE + 17)
   #define EXPORT_GFX_GETVIDEOMODE                          (EXPORT_GFX_BASE + 18)
   #define EXPORT_GFX_GETPIXELOFFSET                        (EXPORT_GFX_BASE + 19)
   #define EXPORT_GFX_GETPIXELWIDTH                         (EXPORT_GFX_BASE + 20)
   #define EXPORT_GFX_SETDEFAULTCOLORS                      (EXPORT_GFX_BASE + 21)
   #define EXPORT_GFX_GFXCOPYRECT                           (EXPORT_GFX_BASE + 22)
   #define EXPORT_GFX_GFXSETRECT                            (EXPORT_GFX_BASE + 23)
   #define EXPORT_GFX_GFXRECTINSIDE                         (EXPORT_GFX_BASE + 24)
   #define EXPORT_GFX_GFXRECTOVERLAPPED                     (EXPORT_GFX_BASE + 25)
   #define EXPORT_GFX_GFXRECTOVERLAPPEDPOINT                (EXPORT_GFX_BASE + 26)
   #define EXPORT_GFX_GFXBITBLT                             (EXPORT_GFX_BASE + 27)
   #define EXPORT_GFX_GFXBANKBITBLT                         (EXPORT_GFX_BASE + 28)
   #define EXPORT_GFX_DRAWPIXELFRONT                        (EXPORT_GFX_BASE + 29)
   #define EXPORT_GFX_DRAWPIXELBACK                         (EXPORT_GFX_BASE + 30)
   #define EXPORT_GFX_DRAWPIXELBANK                         (EXPORT_GFX_BASE + 31)
   #define EXPORT_GFX_DRAWSEGMENTS                          (EXPORT_GFX_BASE + 32)
   #define EXPORT_GFX_DRAWCIRCLE                            (EXPORT_GFX_BASE + 33)
   #define EXPORT_GFX_DRAWFILLEDCIRCLE                      (EXPORT_GFX_BASE + 34)
   #define EXPORT_GFX_DRAWLINE                              (EXPORT_GFX_BASE + 35)
   #define EXPORT_GFX_DRAWLINEEX                            (EXPORT_GFX_BASE + 36)
   #define EXPORT_GFX_DRAWRECTANGLE                         (EXPORT_GFX_BASE + 37)
   #define EXPORT_GFX_DRAWFILLEDRECTANGLE                   (EXPORT_GFX_BASE + 38)
   #define EXPORT_GFX_DRAWTEXTWITHFONT                      (EXPORT_GFX_BASE + 39)
   #define EXPORT_GFX_DRAWTEXTWITHFONTEX                    (EXPORT_GFX_BASE + 40)
   #define EXPORT_GFX_GETFONTMETRICS                        (EXPORT_GFX_BASE + 41)
   #define EXPORT_GFX_DRAWTEXTSCALED                        (EXPORT_GFX_BASE + 42)
   #define EXPORT_GFX_DRAWWINDOWGADGET                      (EXPORT_GFX_BASE + 43)
   #define EXPORT_GFX_DRAWWINDOWGADGETEX                    (EXPORT_GFX_BASE + 44)
   #define EXPORT_GFX_DRAWWINDOWWIDGET                      (EXPORT_GFX_BASE + 45)
   #define EXPORT_GFX_DRAWWINDOWICON                        (EXPORT_GFX_BASE + 46)
   #define EXPORT_GFX_DRAWWINDOWICONEX                      (EXPORT_GFX_BASE + 47)
   #define EXPORT_GFX_DRAWWINDOWICONSCALED                  (EXPORT_GFX_BASE + 48)
   #define EXPORT_GFX_GETFONTHEIGHT                         (EXPORT_GFX_BASE + 49)
   #define EXPORT_GFX_GETFONTWIDTH                          (EXPORT_GFX_BASE + 50)
   #define EXPORT_GFX_MOUSEPOINTERINIT                      (EXPORT_GFX_BASE + 51)
   #define EXPORT_GFX_SETMOUSEPOINTER                       (EXPORT_GFX_BASE + 52)

#endif