#ifndef __FXOS_GUI_SDK_EXPORTS_IDX__
#define __FXOS_GUI_SDK_EXPORTS_IDX__

   #define EXPORT_GUI_BASE   (0)
   #define EXPORT_GUI_GETDESKTOPWINDOW                      (EXPORT_GUI_BASE + 0)
   #define EXPORT_GUI_CREATEWINDOWCLASS                     (EXPORT_GUI_BASE + 1)
   #define EXPORT_GUI_CREATEWINDOWCLASSEX                   (EXPORT_GUI_BASE + 2)
   #define EXPORT_GUI_REGISTERWINDOWCLASS                   (EXPORT_GUI_BASE + 3)
   #define EXPORT_GUI_CREATEWINDOW                          (EXPORT_GUI_BASE + 4)
   #define EXPORT_GUI_CREATEWINDOWEX                        (EXPORT_GUI_BASE + 5)
   #define EXPORT_GUI_SETWINDOWDATA                         (EXPORT_GUI_BASE + 6)
   #define EXPORT_GUI_GETWINDOWDATA                         (EXPORT_GUI_BASE + 7)
   #define EXPORT_GUI_LOADDIALOG                            (EXPORT_GUI_BASE + 8)
   #define EXPORT_GUI_CLOSEWINDOW                           (EXPORT_GUI_BASE + 9)
   #define EXPORT_GUI_DESTROYWINDOW                         (EXPORT_GUI_BASE + 10)
   #define EXPORT_GUI_REGISTERMOUSEPOINTERCLASS             (EXPORT_GUI_BASE + 11)
   #define EXPORT_GUI_LOADFONTCLASS                         (EXPORT_GUI_BASE + 12)
   #define EXPORT_GUI_REGISTERFONTCLASS                     (EXPORT_GUI_BASE + 13)
   #define EXPORT_GUI_GETFONTCLASS                          (EXPORT_GUI_BASE + 14)
   #define EXPORT_GUI_LOADRESOURCE                          (EXPORT_GUI_BASE + 15)
   #define EXPORT_GUI_GETSTRINGTABLEENTRY                   (EXPORT_GUI_BASE + 16)
   #define EXPORT_GUI_REGISTERSTRINGTABLE                   (EXPORT_GUI_BASE + 17)
   #define EXPORT_GUI_GETMOUSEPOINTERCLASS                  (EXPORT_GUI_BASE + 18)
   #define EXPORT_GUI_SETMOUSEPOINTER                       (EXPORT_GUI_BASE + 19)
   #define EXPORT_GUI_SHOWWINDOW                            (EXPORT_GUI_BASE + 20)
   #define EXPORT_GUI_CLIENTTOGLOBALCOORDINATES             (EXPORT_GUI_BASE + 21)
   #define EXPORT_GUI_GLOBALTOCLIENTCOORDINATES             (EXPORT_GUI_BASE + 22)
   #define EXPORT_GUI_CREATEMENU                            (EXPORT_GUI_BASE + 23)
   #define EXPORT_GUI_CLOSEMENU                             (EXPORT_GUI_BASE + 24)
   #define EXPORT_GUI_SELECTMENU                            (EXPORT_GUI_BASE + 25)
   #define EXPORT_GUI_HIGHLIGHTMENU                         (EXPORT_GUI_BASE + 26)
   #define EXPORT_GUI_CREATEMENURESOURCE                    (EXPORT_GUI_BASE + 27)
   #define EXPORT_GUI_ADDMENUITEM                           (EXPORT_GUI_BASE + 28)
   #define EXPORT_GUI_SETMENUITEMATTRIBUTE                  (EXPORT_GUI_BASE + 29)
   #define EXPORT_GUI_SETMENUSTATE                          (EXPORT_GUI_BASE + 30)
   #define EXPORT_GUI_SENDMENUACCELERATOR                   (EXPORT_GUI_BASE + 31)
   #define EXPORT_GUI_SENDMENUACCELERATORITEM               (EXPORT_GUI_BASE + 32)
   #define EXPORT_GUI_CREATEBUTTON                          (EXPORT_GUI_BASE + 33)
   #define EXPORT_GUI_CREATETEXTBOX                         (EXPORT_GUI_BASE + 34)
   #define EXPORT_GUI_CREATEVERTICALSCROLLBAR               (EXPORT_GUI_BASE + 35)
   #define EXPORT_GUI_CREATEMSGBOX                          (EXPORT_GUI_BASE + 36)
   #define EXPORT_GUI_CENTERWINDOW                          (EXPORT_GUI_BASE + 37)
   #define EXPORT_GUI_CENTERBOTTOMWINDOW                    (EXPORT_GUI_BASE + 38)
   #define EXPORT_GUI_MOVEWINDOW                            (EXPORT_GUI_BASE + 39)
   #define EXPORT_GUI_MOVEWINDOWEX                          (EXPORT_GUI_BASE + 40)
   #define EXPORT_GUI_RESIZEWINDOWEX                        (EXPORT_GUI_BASE + 41)
   #define EXPORT_GUI_GETFOCUSWINDOW                        (EXPORT_GUI_BASE + 42)
   #define EXPORT_GUI_ISCHILDWINDOW                         (EXPORT_GUI_BASE + 43)
   #define EXPORT_GUI_SETRECT                               (EXPORT_GUI_BASE + 44)
   #define EXPORT_GUI_CLEARRECT                             (EXPORT_GUI_BASE + 45)
   #define EXPORT_GUI_COPYRECT                              (EXPORT_GUI_BASE + 46)
   #define EXPORT_GUI_DRAWTEXT                              (EXPORT_GUI_BASE + 47)
   #define EXPORT_GUI_DRAWWINDOWTEXTTOPOINT                 (EXPORT_GUI_BASE + 48)
   #define EXPORT_GUI_GETMOUSEPOINT                         (EXPORT_GUI_BASE + 49)
   #define EXPORT_GUI_GETMOUSECLIENTPOINT                   (EXPORT_GUI_BASE + 50)
   #define EXPORT_GUI_DEFAULTWINDOWPROC                     (EXPORT_GUI_BASE + 51)

#endif