#ifndef __FXOS_KERNEL_SDK_EXPORTS_IDX__
#define __FXOS_KERNEL_SDK_EXPORTS_IDX__

   #define EXPORT_KERNEL_BASE   (0)
   #define EXPORT_KERNEL_RAISEEXCEPTION                        (EXPORT_KERNEL_BASE + 0)
   #define EXPORT_KERNEL_GETPROCESS                            (EXPORT_KERNEL_BASE + 1)
   #define EXPORT_KERNEL_GETPROCESSBYNAME                      (EXPORT_KERNEL_BASE + 2)
   #define EXPORT_KERNEL_GETPROCESSLIST                        (EXPORT_KERNEL_BASE + 3)
   #define EXPORT_KERNEL_LAUNCHPROCESS                         (EXPORT_KERNEL_BASE + 4)
   #define EXPORT_KERNEL_CREATEPROCESS                         (EXPORT_KERNEL_BASE + 5)
   #define EXPORT_KERNEL_GETCURRENTPROCESS                     (EXPORT_KERNEL_BASE + 6)
   #define EXPORT_KERNEL_PROCESSSLEEP                          (EXPORT_KERNEL_BASE + 7)
   #define EXPORT_KERNEL_PROCESSTERMINATE                      (EXPORT_KERNEL_BASE + 8)
   #define EXPORT_KERNEL_PROCESSSTART                          (EXPORT_KERNEL_BASE + 9)
   #define EXPORT_KERNEL_PROCESSWAIT                           (EXPORT_KERNEL_BASE + 10)
   #define EXPORT_KERNEL_PROCESSSIGNAL                         (EXPORT_KERNEL_BASE + 11)
   #define EXPORT_KERNEL_DEBUGOUT                              (EXPORT_KERNEL_BASE + 12)
   #define EXPORT_KERNEL_DEBUGNSTRING                          (EXPORT_KERNEL_BASE + 13)
   #define EXPORT_KERNEL_DEBUGCHAR                             (EXPORT_KERNEL_BASE + 14)
   #define EXPORT_KERNEL_DEBUGPOINTER                          (EXPORT_KERNEL_BASE + 15)
   #define EXPORT_KERNEL_DEBUGINTEGER                          (EXPORT_KERNEL_BASE + 16)
   #define EXPORT_KERNEL_GETMOUSECLIENTPOINT                   (EXPORT_KERNEL_BASE + 17)
   #define EXPORT_KERNEL_DEBUGLONG                             (EXPORT_KERNEL_BASE + 18)
   #define EXPORT_KERNEL_DEBUGHEX                              (EXPORT_KERNEL_BASE + 19)
   #define EXPORT_KERNEL_DEBUGHEXCHAR                          (EXPORT_KERNEL_BASE + 20)
   #define EXPORT_KERNEL_DEBUGBITS                             (EXPORT_KERNEL_BASE + 21)
   #define EXPORT_KERNEL_DEBUGBYTEARRAY                        (EXPORT_KERNEL_BASE + 22)
   #define EXPORT_KERNEL_DEBUGMESSAGE                          (EXPORT_KERNEL_BASE + 23)
   #define EXPORT_KERNEL_DEBUGSTRINGS                          (EXPORT_KERNEL_BASE + 24)
   #define EXPORT_KERNEL_DEBUGNMESSAGE                         (EXPORT_KERNEL_BASE + 25)
   #define EXPORT_KERNEL_DEBUGNSTRINGS                         (EXPORT_KERNEL_BASE + 26)
   #define EXPORT_KERNEL_DEBUGRECT                             (EXPORT_KERNEL_BASE + 27)
   #define EXPORT_KERNEL_DEBUGCRLF                             (EXPORT_KERNEL_BASE + 28)
   #define EXPORT_KERNEL_DEBUGNODE                             (EXPORT_KERNEL_BASE + 29)
   #define EXPORT_KERNEL_DEBUGNODES                            (EXPORT_KERNEL_BASE + 30)
   #define EXPORT_KERNEL_DEBUGNODELIST                         (EXPORT_KERNEL_BASE + 31)
   #define EXPORT_KERNEL_DEBUGNODESDATA                        (EXPORT_KERNEL_BASE + 32)
   #define EXPORT_KERNEL_DEBUGSTATUS                           (EXPORT_KERNEL_BASE + 33)
   #define EXPORT_KERNEL_DEBUGON                               (EXPORT_KERNEL_BASE + 34)
   #define EXPORT_KERNEL_DEBUGOFF                              (EXPORT_KERNEL_BASE + 35)
   #define EXPORT_KERNEL_GETRTCHOUR                            (EXPORT_KERNEL_BASE + 36)
   #define EXPORT_KERNEL_GETRTCMINUTE                          (EXPORT_KERNEL_BASE + 37)
   #define EXPORT_KERNEL_GETRTCSECOND                          (EXPORT_KERNEL_BASE + 38)
   #define EXPORT_KERNEL_GETRTCMONTH                           (EXPORT_KERNEL_BASE + 39)
   #define EXPORT_KERNEL_GETRTCDAY                             (EXPORT_KERNEL_BASE + 40)
   #define EXPORT_KERNEL_GETRTCYEAR                            (EXPORT_KERNEL_BASE + 41)
   #define EXPORT_KERNEL_GETRTCCENTURY                         (EXPORT_KERNEL_BASE + 42)
   #define EXPORT_KERNEL_GETFIRMWAREDATEDAY                    (EXPORT_KERNEL_BASE + 43)
   #define EXPORT_KERNEL_GETFIRMWAREDATEMONTH                  (EXPORT_KERNEL_BASE + 44)
   #define EXPORT_KERNEL_GETFIRMWAREDATEYEAR                   (EXPORT_KERNEL_BASE + 45)
   #define EXPORT_KERNEL_GETHARDWAREVERSIONMAJOR               (EXPORT_KERNEL_BASE + 46)
   #define EXPORT_KERNEL_GETHARDWAREVERSIONMINOR               (EXPORT_KERNEL_BASE + 47)
   #define EXPORT_KERNEL_MEMORYCOPY                            (EXPORT_KERNEL_BASE + 48)
   #define EXPORT_KERNEL_MEMORYALLOC                           (EXPORT_KERNEL_BASE + 49)
   #define EXPORT_KERNEL_MEMORYDEALLOC                         (EXPORT_KERNEL_BASE + 50)
   #define EXPORT_KERNEL_MEMORYLOCK                            (EXPORT_KERNEL_BASE + 51)
   #define EXPORT_KERNEL_MEMORYUNLOCK                          (EXPORT_KERNEL_BASE + 52)
   #define EXPORT_KERNEL_HEAPALLOC                             (EXPORT_KERNEL_BASE + 53)
   #define EXPORT_KERNEL_HEAPDEALLOC                           (EXPORT_KERNEL_BASE + 54)
   #define EXPORT_KERNEL_SEGMENTLOAD                           (EXPORT_KERNEL_BASE + 55)
   #define EXPORT_KERNEL_SEGMENTLOCK                           (EXPORT_KERNEL_BASE + 56)
   #define EXPORT_KERNEL_SEGMENTUNLOCK                         (EXPORT_KERNEL_BASE + 57)
   #define EXPORT_KERNEL_SEGMENTUNLOAD                         (EXPORT_KERNEL_BASE + 58)
   #define EXPORT_KERNEL_GETSEGMENTINFO                        (EXPORT_KERNEL_BASE + 59)

#endif